import './components/form.js'
import './components/header.js'
import './components/main.js'
import './components/menu.js'
import './components/not-found.js'
import './components/page.js'
import './components/table.js'
import './components/title.js'
